version: "2"
run:
  go: "1.25"
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m
  build-tags:
    - integ
    - integfuzz
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - decorder
    - dogsled
    - errcheck
    - errchkjson
    - errorlint
    - gocritic
    - godox
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocritic:
      disabled-checks:
        - exitAfterDefer
    gosec:
      excludes:
        - G102
        - G112
        - G306
        - G401
        - G402
        - G404
        - G501
      severity: low
      confidence: low
    misspell:
      ignore-rules:
        - cancelled
        - marshalled
    staticcheck:
      checks:
        - all
        - -ST1003
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - dupl
          - errcheck
          - funlen
          - goconst
          - gosec
          - noctx
          - wrapcheck
        path: _test\.go$|^tests/|^samples/
      - linters:
          - revive
          - staticcheck
        text: use underscores in Go names
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - unparam
        text: is always false
    paths:
      - .*\.pb\.go
      - .*\.gen\.go
      - genfiles$
      - vendor$
      - bin$
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/fatedier/frp/)
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go
      - .*\.gen\.go
      - genfiles$
      - vendor$
      - bin$
      - third_party$
      - builtin$
      - examples$
